---
- hosts: wordpress
  remote_user: linux
  become: yes
  become_user: root
  role:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: nginx, tags: nginx }
    - { role: deploy, tags: deploy }
